export const categories = [
  { name: 'Comida' },
  { name: 'Tecnología' },
  { name: 'Viajes' },
  { name: 'Salud' },
  { name: 'Educación' },
  { name: 'Deportes' },
  { name: 'Entretenimiento' },
  { name: 'Negocios' },
  { name: 'Arte' },
  { name: 'Ciencia' },
  { name: 'Música' },
  { name: 'Cine' },
  { name: 'Fotografía' },
  { name: 'Literatura' },
  { name: 'Historia' },
  { name: 'Política' },
  { name: 'Medio Ambiente' },
  { name: 'Moda' },
  { name: 'Finanzas' },
  { name: 'Arquitectura' },
  { name: 'Diseño' },
  { name: 'Cocina' },
  { name: 'Cultura' },
  { name: 'Psicología' },
  { name: 'Desarrollo Personal' },
  { name: 'Marketing' },
  { name: 'Emprendimiento' },
  { name: 'Gestión de Talento' },
  { name: 'Relaciones Internacionales' },
  { name: 'Automotriz' },
];