// tagsData.js

export const tags = [
  { name: 'Gastronomía' },
  { name: 'Vinos' },
  { name: 'Coctelería' },
  { name: 'Fotografía' },
  { name: 'Viajes' },
  { name: 'Historia' },
  { name: 'Cine' },
  { name: 'Música' },
  { name: 'Deportes' },
  { name: 'Medio Ambiente' },
  { name: 'Salud Mental' },
  { name: 'Desarrollo Personal' },
  { name: 'Finanzas Personales' },
  { name: 'Emprendimiento' },
  { name: 'Marketing' },
  { name: 'Psicología' },
  { name: 'Filosofía' },
  { name: 'Ciencia' },
  { name: 'Astronomía' },
  { name: 'Ecología' },
  { name: 'Arte' },
  { name: 'Literatura' },
  { name: 'Teatro' },
  { name: 'Moda' },
  { name: 'Jardinería' },
  { name: 'Fauna Silvestre' },
  { name: 'Idiomas' },
  { name: 'Educación' },
  { name: 'Política' },
  { name: 'Derecho' },
  { name: 'Historia del Arte' },
  { name: 'Artesanía' },
  { name: 'Motivación' },
  { name: 'Negocios' },
  { name: 'Inversiones' },
  { name: 'Cultura Pop' },
  { name: 'Videojuegos' },
  { name: 'Redes Sociales' },
  { name: 'Automóviles' },
  { name: 'Aventura' },
  { name: 'Espiritualidad' },
  { name: 'Bienestar' },
  { name: 'Nutrición' },
  { name: 'Ciclismo' },
  { name: 'Senderismo' },
  { name: 'Yoga' },
  { name: 'Meditación' },
  { name: 'Podcasting' },
  { name: 'DIY' },
  { name: 'Relaciones Personales' },
];
